version: "2.1"

services:
  myapp:
    image: alpine:latest
    restart: always
    command: "sh -c 'while :; do sleep 1; done'"

  crontab:
    build: .
    restart: always
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
    # - "/usr/bin/docker:/usr/bin/docker:ro"
     - "/srv/docer/crontab/config.json:/opt/crontab/config.json:rw"
